title: Projet de S2-SNE - Récepteur d'une liaison série  en conception Full Synchrone
# description: Architect is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
